# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib f3t, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_f3t__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_f3t__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Compute FFT magnitudes of a real-valued input slice.
#' Returns a Vec<f64> of magnitudes (length = input.len()).
#' #@export
`fft_magnitude` <- function(`input`) {
  .Call(savvy_fft_magnitude__impl, `input`)
}

#' Compute FFT magnitudes of a real-valued input slice.
#' Returns a Vec<f64> of magnitudes (length = input.len()).
#' #@export
`fft_magnitude_sliding` <- function(`input`) {
  .Call(savvy_fft_magnitude_sliding__impl, `input`)
}

#' Compute FFT magnitudes of a real-valued input slice.
#' Returns a Vec<f64> of magnitudes (length = input.len()).
#' # @export
`fft_parallel` <- function(`input`) {
  .Call(savvy_fft_parallel__impl, `input`)
}

#' Parallel FFT over all windows
#' @export
`fft_sliding_parallel` <- function(`signal`, `window_size`, `hop_size`, `threads`) {
  .Call(savvy_fft_sliding_parallel__impl, `signal`, `window_size`, `hop_size`, `threads`)
}

#' Parallel FFT over all windows
#' @export
`generate_sine_mixture` <- function(`duration`, `sampling_rate`, `freqs`, `amps`, `phases`, `noise_sd`) {
  .Call(savvy_generate_sine_mixture__impl, `duration`, `sampling_rate`, `freqs`, `amps`, `phases`, `noise_sd`)
}


